import type { ScanResult, RecommendationResult, AdapterOutput, GeneratedFile } from "../types/index.js";
import { BaseAdapter } from "./base-adapter.js";

export class CodexAdapter extends BaseAdapter {
  readonly tool = "codex" as const;
  readonly displayName = "OpenAI Codex";

  generate(scan: ScanResult, recommendations: RecommendationResult): AdapterOutput {
    const files: GeneratedFile[] = [];
    const warnings: string[] = [];

    const agentsMd = this.generateAgentsMd(scan, recommendations);
    files.push(agentsMd);

    // Check 32KB limit
    if (agentsMd.sizeBytes > 32768) {
      warnings.push(`AGENTS.md is ${(agentsMd.sizeBytes / 1024).toFixed(1)}KB — exceeds Codex 32KB limit. Consider reducing content.`);
    }

    return { tool: "codex", files, totalSize: agentsMd.sizeBytes, sizeUnit: "bytes", warnings };
  }

  private generateAgentsMd(scan: ScanResult, rec: RecommendationResult): GeneratedFile {
    const lines: string[] = [];
    lines.push(`# ${scan.projectName}`);
    lines.push("");
    lines.push(`> Generated by [dotti](https://dotti.dev) — AI config from your code`);
    lines.push("");

    // Project context
    lines.push("## Project Overview");
    const techs = [
      ...scan.techStack.languages.slice(0, 3).map((l) => l.name),
      ...scan.techStack.frameworks.map((f) => f.name),
      ...scan.techStack.buildTools.map((b) => b.name),
    ];
    lines.push(`Tech stack: ${techs.join(", ")}`);
    lines.push("");

    // Rules as instructions
    for (const rule of rec.rules) {
      lines.push(rule.content);
      lines.push("");
    }

    // Agent descriptions as sections
    if (rec.agents.length > 0) {
      lines.push("## Agent Roles");
      lines.push("");
      for (const agent of rec.agents) {
        lines.push(`### ${agent.name}`);
        lines.push(agent.description);
        lines.push(`Files: ${agent.relevantFiles.join(", ")}`);
        lines.push("");
      }
    }

    const content = lines.join("\n");
    return {
      path: "AGENTS.md",
      content,
      description: "Agent instructions for OpenAI Codex",
      sizeBytes: Buffer.byteLength(content, "utf-8"),
    };
  }
}
