import type { ScanResult, RecommendationResult, AdapterOutput, GeneratedFile } from "../types/index.js";
import { BaseAdapter } from "./base-adapter.js";

export class GeminiAdapter extends BaseAdapter {
  readonly tool = "gemini" as const;
  readonly displayName = "Gemini CLI";

  generate(scan: ScanResult, recommendations: RecommendationResult): AdapterOutput {
    const files: GeneratedFile[] = [];
    const warnings: string[] = [];

    files.push(this.generateGeminiMd(scan, recommendations));

    // Note: Gemini loads GEMINI.md hierarchically (up & down tree)
    // We only generate root-level to avoid context pollution
    warnings.push(
      "Gemini CLI loads GEMINI.md files from all parent & child directories. " +
      "dotti generates only the root GEMINI.md to avoid context pollution."
    );

    const totalSize = files.reduce((sum, f) => sum + f.sizeBytes, 0);
    return { tool: "gemini", files, totalSize, sizeUnit: "tokens", warnings };
  }

  private generateGeminiMd(scan: ScanResult, rec: RecommendationResult): GeneratedFile {
    const lines: string[] = [];

    lines.push(`# ${scan.projectName}`);
    lines.push("");
    lines.push(`> Generated by [dotti](https://dotti.dev)`);
    lines.push("");

    // Tech stack context
    lines.push("## Project Context");
    const techs = [
      ...scan.techStack.languages.slice(0, 3).map((l) => `${l.name} (${l.fileCount} files)`),
      ...scan.techStack.frameworks.map((f) => f.name),
      ...scan.techStack.buildTools.map((b) => b.name),
      ...scan.techStack.testing.map((t) => `${t.name} (${t.type})`),
      ...scan.techStack.database.map((d) => d.name),
      ...scan.techStack.styling.map((s) => s.name),
    ];
    for (const tech of techs) {
      lines.push(`- ${tech}`);
    }
    lines.push("");

    // Rules
    for (const rule of rec.rules) {
      lines.push(rule.content);
      lines.push("");
    }

    // Skills / agent guidance
    if (rec.agents.length > 0) {
      lines.push("## Skills");
      for (const agent of rec.agents) {
        lines.push(`### ${agent.name}`);
        lines.push(agent.description);
        lines.push(`Triggers: ${agent.triggers.join(", ")}`);
        lines.push("");
      }
    }

    const content = lines.join("\n");
    return {
      path: "GEMINI.md",
      content,
      description: "Project context and skills for Gemini CLI",
      sizeBytes: Buffer.byteLength(content, "utf-8"),
    };
  }
}
